version: '3'

services:

  word2vec:
    build:
      context: .
    volumes:
      - ./word2vec:/src/entity-manager
      - ./tests:/tests
    ports:
      - 10011:9099
    environment:
    - ENTITY_MANAGER_SERVER_PORT=9099